port: 8080
redis:
  host: "119.23.252.204"
  port: 6379
  password: "redis"
  db: 0
  pool_size: 100
minIO:
  endpoint: "119.23.252.204:9000"
  username: "username"
  password: "password"
mongo:
  name: "dousheng"
  host: "125.73.58.176:5208"
  user: "chaiquan"
  pwd:  "qwer1234"
