port: 8080
redis:
  host: "122.9.122.77"
  port: 8635
  password: "Bytedance@2022"
  db: 0
  pool_size: 100
minIO:
  endpoint: "119.23.252.204:9000"
  username: "username"
  password: "password"
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
mongo:
  name: "dousheng"
  host: "125.73.58.176"
  post: 5208
  user: "chaiquan"
  pwd:  ""
